configuracion/urls.py
from django.urls import path, include
from .views import AccesoListView, AccesoCreateView, AccesoUpdateView

app_name = 'cofiguracion'
urlpatterns = [

    path('acceso/listar', AccesoListView.as_view(), name='acceso_listar'),
    path('acceso/crear', AccesoCreateView.as_view(), name='acceso_crear'),
    path('acceso/actualizar/<int:pk>', AccesoUpdateView.as_view(), name='acceso_actualizar'),

]

evento/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from inscripcion.views import IdexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inscripcion/', include('inscripcion.urls', namespace='inscripcion')),
    path('configuracion/', include('configuracion.urls', namespace='configuracion')),
    path('', IdexTemplateView.as_view(), name='index'),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inscripcion/urls.py
from django.urls import path, include

from inscripcion.views import EventoDetailView
from .views import EventoView

app_name = 'inscripcion'
urlpatterns = [

    path('eventos', EventoView.as_view(), name='eventos'),
    path('evento/<slug:pk>', EventoDetailView.as_view(), name='formulario'),
]

configuracion/models.py
from django.db import models


class Evento(models.Model):
    nombre = models.CharField(u"Nombre", max_length=50)
    cuenta = models.CharField(u"Cuenta", max_length=50)
    descripcion = models.TextField(u"Descripción")
    estado = models.BooleanField()

    class Meta:
        verbose_name = "Evento"
        verbose_name_plural = "Eventos"

    def __str__(self):
        return self.nombre


class Acceso(models.Model):
    token = models.TextField(u"Token")
    dominio = models.URLField(max_length=150)
    servicio = models.CharField(u"Servicio", max_length=50)
    estado = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Acceso"
        verbose_name_plural = "Accesos"

    def __str__(self):
        return self.token

inscripcion/models.py
from django.db import models

# Create your models here.

personas/models.py
from django.db import models

# Create your models here.

configuracion/forms.py
from django import forms
from .models import Acceso


class AccesoModelForm(forms.ModelForm):
    class Meta:
        model = Acceso
        exclude = ("estado",)

configuracion/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView

from .models import Acceso
from .forms import AccesoModelForm


class AccesoListView(ListView):
    model = Acceso
    template_name = "configuracion/acceso/list.html"


class AccesoCreateView(CreateView):
    model = Acceso
    template_name = "configuracion/acceso/form.html"
    form_class = AccesoModelForm
    success_url = reverse_lazy("configuracion:acceso_listar")


class AccesoUpdateView(UpdateView):
    model = AccesoModelForm
    template_name = "configuracion/acceso/form.html"
    form_class = AccesoModelForm
    success_url = reverse_lazy("configuracion:acceso_listar")

inscripcion/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView
import requests

from configuracion.models import Acceso, Evento
from configuracion.views import AccesoUpdateView


class IdexTemplateView(TemplateView):
    template_name = 'inscripcion/index.html'


class EventoView(TemplateView):
    template_name = "inscripcion/view.html"

    def get_context_data(self, **kwargs):
        context = super(EventoView, self).get_context_data(**kwargs)
        # dni = self.request.GET.get("dni")
        # evento_id = self.request.GET.get("evento")
        #
        # evento = Evento.objects.get(id=evento_id)
        #
        # acceso = Acceso.objects.filter(estado=True)[0]
        # url = acceso.dominio + acceso.servicio + "/" + dni + "/" + evento.cueenta + "/"
        # r = requests.get(url, headers={
        #     'Authorization': "%s %s" % ("Bearer", acceso.token)})
        # print(r.json())
        context['eventos'] = Evento.objects.filter(estado=True)

        return context


class EventoDetailView(DetailView):
    model = Evento
    template_name = "inscripcion/detail.html"

    def get_context_data(self, **kwargs):
        context = super(EventoDetailView, self).get_context_data(**kwargs)
        documento = self.request.GET.get("documento")
        print(documento)
        if documento:
            print(self.get_object())
            acceso = Acceso.objects.filter(estado=True)[0]
            url = acceso.dominio + acceso.servicio + "/" + documento + "/" + self.get_object().cuenta + "/"
            r = requests.get(url, headers={
                'Authorization': "%s %s" % ("Bearer", acceso.token)})
            if r.json():
                context['pago'] = r.json()[0]
            else:
                context['pago'] = None
        return context

personas/views.py
from django.shortcuts import render

# Create your views here.

configuracion/templates/configuracion/acceso/form.html
{% extends "base.html" %}


{% block content %}
    <div class="mdl-card mdl-shadow--2dp employer-form" action="#">
        <div class="mdl-card__title">
            <h2>Form</h2>
            <div class="mdl-card__subtitle">Please complete the form</div>
        </div>

        <div class="mdl-card__supporting-text">
            <form method="post" class="form">
                {% csrf_token %}
                <div class="form__article">
                    <h3>Personal data</h3>

                    <div class="mdl-grid">
                        <div class="mdl-cell mdl-cell--6-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            <input class="mdl-textfield__input" name="dominio" type="text" id="dominio_id"/>
                            {{ form.dominio.errors }}
                            <label class="mdl-textfield__label" for="dominio_id">Dominio</label>
                        </div>
                        <div class="mdl-cell mdl-cell--6-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            <input class="mdl-textfield__input" name="servicio" type="text" id="servicio_id"/>
                            <label class="mdl-textfield__label" for="servicio_id">Servicio</label>
                            {{ form.servicio.errors }}
                        </div>

                        <div class="mdl-cell mdl-cell--12-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            <input class="mdl-textfield__input" type="text" name="token" id="token_id"/>
                            <label class="mdl-textfield__label" for="token_id">Token</label>
                            {{ form.token.errors }}
                        </div>
                    </div>
                </div>
                <div class="form__action">

                    <button id="submit_button" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
                        Guardar
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

configuracion/templates/configuracion/acceso/list.html
{% extends "base.html" %}


{% block content %}

    <div class="mdl-cell mdl-cell--12-col-desktop mdl-cell--12-col-tablet mdl-cell--4-col-phone ">
        <a class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored-blue"
           href="{% url 'cofiguracion:acceso_crear' %}">
            <i class="material-icons">create</i>
            Crear Acceso
        </a>

        <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp projects-table">
            <thead>
            <tr>
                <th class="mdl-data-table__cell--non-numeric">#</th>
                <th class="mdl-data-table__cell--non-numeric">Dominio</th>
                <th class="mdl-data-table__cell--non-numeric">Estado</th>
                <th class="mdl-data-table__cell--non-numeric">Fecha de Registro</th>
                <th class="mdl-data-table__cell--non-numeric">Acces Token</th>

            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">{{ forloop.counter }}</td>
                    <td class="mdl-data-table__cell--non-numeric">
                        {{ object.dominio }}

                    </td>
                    <td class="mdl-data-table__cell--non-numeric">

                        {% if object.estado %}
                            <span class="label label--mini background-color--mint">Activo</span>
                        {% else %}
                            <span class="label label--mini background-color--secondary"></span>
                        {% endif %}

                    </td>
                    <td class="mdl-data-table__cell--non-numeric">{{ object.created_at }}</td>
                    <td class="mdl-data-table__cell--non-numeric">{{ object.token }}</td>

                </tr>
            {% endfor %}


            </tbody>
        </table>
    </div>
{% endblock content %}

inscripcion/templates/inscripcion/detail.html
{% extends "base.html" %}


{% block content %}

    <div class="mdl-card mdl-shadow--2dp employer-form" action="#">
        <div class="mdl-card__title">
            <h2>Formulario {{ object.nombre }}</h2>
            <div class="mdl-card__subtitle">Please complete the form</div>
        </div>

        <div class="mdl-card__supporting-text">
            <form action="#" class="form" method="get">
                <div class="form__article">
                    <h3>Dato Personal</h3>
                    <div class="mdl-grid">
                        <div class="mdl-cell mdl-cell--12-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            <input class="mdl-textfield__input" type="text" id="company_email"
                                   value="{{ request.GET.documento }}" name="documento"/>
                            <label class="mdl-textfield__label" for="company_email">Número de Documento</label>
                        </div>
                    </div>
                </div>

                <div class="form__action">

                    <button type="submit" id="submit_button"
                            class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
                        Validar
                    </button>
                </div>
            </form>
        </div>
    </div>


    {% if pago %}
        <div class="mdl-cell mdl-cell--12-col-desktop mdl-cell--12-col-tablet mdl-cell--12-col-phone">
            <div class="mdl-card mdl-shadow--2dp line-chart">
                <div class="mdl-card__title">
                    <h2 class="mdl-card__title-text">Validación exitosa</h2>
                </div>
                <div class="mdl-card__supporting-text">
                    <ul>
                        <li><strong>Persona:</strong>{{ pago.person_name }}</li>
                        <li><strong>Transacción: </strong>{{ pago.number_transaction }}</li>
                        <li><strong>Detalle de deposito:</strong>{{ pago.institution_name }}</li>
                    </ul>

                </div>
            </div>
        </div>
    {% else %}
        <div class="mdl-cell mdl-cell--12-col-desktop mdl-cell--12-col-tablet mdl-cell--12-col-phone">
            <div class="mdl-card mdl-shadow--2dp line-chart">
                <div class="mdl-card__title">
                    <h2 class="mdl-card__title-text">Validación Errada</h2>
                </div>
                <div class="mdl-card__supporting-text">
                   <p>No se encontro pago alguno</p>
                </div>
            </div>
        </div>
    {% endif %}




{% endblock content %}

inscripcion/templates/inscripcion/view.html
{% extends "base.html" %}



{% block content %}
    <div class="mdl-grid ui-cards">
        <div class="mdl-cell mdl-cell--12-col-desktop mdl-cell--12-col-tablet mdl-cell--4-col-phone">
            <h3>Eventos</h3>
        </div>

        {% for evento in eventos %}
            <div class="mdl-cell mdl-cell--4-col-desktop mdl-cell--4-col-tablet mdl-cell--2-col-phone">
                <div class="mdl-card mdl-shadow--2dp">
                    <div class="mdl-card__title">
                        <h2 class="mdl-card__title-text">{{ evento.nombre }}</h2>
                    </div>
                    <div class="mdl-card__supporting-text">

                        {{ evento.descripcion }}

                    </div>
                    <div class="mdl-card__actions mdl-card--border">
                        <a class="mdl-button color-text--light-blue mdl-js-button mdl-js-ripple-effect"
                           href="{% url 'inscripcion:formulario' evento.id %}">
                            Registrar
                        </a>
                    </div>
                </div>

            </div>
        {% endfor %}

        <div class="mdl-cell mdl-cell--12-col-desktop mdl-cell--12-col-tablet mdl-cell--4-col-phone">

        </div>
        <div class="mdl-cell mdl-cell--12-col-desktop mdl-cell--12-col-tablet mdl-cell--4-col-phone">

        </div>
        <div class="mdl-cell mdl-cell--12-col-desktop mdl-cell--12-col-tablet mdl-cell--4-col-phone">

        </div>
        <div class="mdl-cell mdl-cell--12-col-desktop mdl-cell--12-col-tablet mdl-cell--4-col-phone">

        </div>
        <div class="mdl-cell mdl-cell--12-col-desktop mdl-cell--12-col-tablet mdl-cell--4-col-phone">

        </div>
    </div>
{% endblock content %}

templates/assets/header.html
{% load static %}
<header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
        <div class="mdl-layout-spacer"></div>
        <!-- Search-->
        <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
            <label class="mdl-button mdl-js-button mdl-button--icon" for="search">
                <i class="material-icons">search</i>
            </label>

            <div class="mdl-textfield__expandable-holder">
                <input class="mdl-textfield__input" type="text" id="search"/>
                <label class="mdl-textfield__label" for="search">Enter your query...</label>
            </div>
        </div>

        <div class="material-icons mdl-badge mdl-badge--overlap mdl-button--icon notification" id="notification"
             data-badge="23">
            notifications_none
        </div>
        <!-- Notifications dropdown-->
        <ul class="mdl-menu mdl-list mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right mdl-shadow--2dp notifications-dropdown"
            for="notification">
            <li class="mdl-list__item">
                You have 23 new notifications!
            </li>
            <li class="mdl-menu__item mdl-list__item list__item--border-top">
                    <span class="mdl-list__item-primary-content">
                        <span class="mdl-list__item-avatar background-color--primary">
                            <i class="material-icons">plus_one</i>
                        </span>
                        <span>You have 3 new orders.</span>
                    </span>
                <span class="mdl-list__item-secondary-content">
                      <span class="label">just now</span>
                    </span>
            </li>
            <li class="mdl-menu__item mdl-list__item list__item--border-top">
                    <span class="mdl-list__item-primary-content">
                        <span class="mdl-list__item-avatar background-color--secondary">
                            <i class="material-icons">error_outline</i>
                        </span>
                      <span>Database error</span>
                    </span>
                <span class="mdl-list__item-secondary-content">
                      <span class="label">1 min</span>
                    </span>
            </li>
            <li class="mdl-menu__item mdl-list__item list__item--border-top">
                    <span class="mdl-list__item-primary-content">
                        <span class="mdl-list__item-avatar background-color--primary">
                            <i class="material-icons">new_releases</i>
                        </span>
                      <span>The Death Star is built!</span>
                    </span>
                <span class="mdl-list__item-secondary-content">
                      <span class="label">2 hours</span>
                    </span>
            </li>
            <li class="mdl-menu__item mdl-list__item list__item--border-top">
                    <span class="mdl-list__item-primary-content">
                        <span class="mdl-list__item-avatar background-color--primary">
                            <i class="material-icons">mail_outline</i>
                        </span>
                      <span>You have 4 new mails.</span>
                    </span>
                <span class="mdl-list__item-secondary-content">
                      <span class="label">5 days</span>
                    </span>
            </li>
            <li class="mdl-list__item list__item--border-top">
                <button href="#" class="mdl-button mdl-js-button mdl-js-ripple-effect">ALL NOTIFICATIONS</button>
            </li>
        </ul>

        <div class="material-icons mdl-badge mdl-badge--overlap mdl-button--icon message" id="inbox" data-badge="4">
            mail_outline
        </div>
        <!-- Messages dropdown-->
        <ul class="mdl-menu mdl-list mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right mdl-shadow--2dp messages-dropdown"
            for="inbox">
            <li class="mdl-list__item">
                You have 4 new messages!
            </li>
            <li class="mdl-menu__item mdl-list__item mdl-list__item--two-line list__item--border-top">
                    <span class="mdl-list__item-primary-content">
                        <span class="mdl-list__item-avatar background-color--primary">
                            <text>A</text>
                        </span>
                        <span>Alice</span>
                        <span class="mdl-list__item-sub-title">Birthday Party</span>
                    </span>
                <span class="mdl-list__item-secondary-content">
                      <span class="label label--transparent">just now</span>
                    </span>
            </li>
            <li class="mdl-menu__item mdl-list__item mdl-list__item--two-line list__item--border-top">
                    <span class="mdl-list__item-primary-content">
                        <span class="mdl-list__item-avatar background-color--baby-blue">
                            <text>M</text>
                        </span>
                        <span>Mike</span>
                        <span class="mdl-list__item-sub-title">No theme</span>
                    </span>
                <span class="mdl-list__item-secondary-content">
                      <span class="label label--transparent">5 min</span>
                    </span>
            </li>
            <li class="mdl-menu__item mdl-list__item mdl-list__item--two-line list__item--border-top">
                    <span class="mdl-list__item-primary-content">
                        <span class="mdl-list__item-avatar background-color--cerulean">
                            <text>D</text>
                        </span>
                        <span>Darth</span>
                        <span class="mdl-list__item-sub-title">Suggestion</span>
                    </span>
                <span class="mdl-list__item-secondary-content">
                      <span class="label label--transparent">23 hours</span>
                    </span>
            </li>
            <li class="mdl-menu__item mdl-list__item mdl-list__item--two-line list__item--border-top">
                    <span class="mdl-list__item-primary-content">
                        <span class="mdl-list__item-avatar background-color--mint">
                            <text>D</text>
                        </span>
                        <span>Don McDuket</span>
                        <span class="mdl-list__item-sub-title">NEWS</span>
                    </span>
                <span class="mdl-list__item-secondary-content">
                      <span class="label label--transparent">30 Nov</span>
                    </span>
            </li>
            <li class="mdl-list__item list__item--border-top">
                <button href="#" class="mdl-button mdl-js-button mdl-js-ripple-effect">SHOW ALL MESSAGES</button>
            </li>
        </ul>

        <div class="avatar-dropdown" id="icon">
            <span>Pacifi</span>
            <img src="{% static 'custom/images/Icon_header.png' %}">
        </div>
        <!-- Account dropdawn-->
        <ul class="mdl-menu mdl-list mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect mdl-shadow--2dp account-dropdown"
            for="icon">
            <li class="mdl-list__item mdl-list__item--two-line">
                    <span class="mdl-list__item-primary-content">
                        <span class="material-icons mdl-list__item-avatar"></span>
                        <span>Luke</span>
                        <span class="mdl-list__item-sub-title">Luke@skywalker.com</span>
                    </span>
            </li>
            <li class="list__item--border-top"></li>
            <li class="mdl-menu__item mdl-list__item">
                    <span class="mdl-list__item-primary-content">
                        <i class="material-icons mdl-list__item-icon">account_circle</i>
                        My account
                    </span>
            </li>
            <li class="mdl-menu__item mdl-list__item">
                    <span class="mdl-list__item-primary-content">
                        <i class="material-icons mdl-list__item-icon">check_box</i>
                        My tasks
                    </span>
                <span class="mdl-list__item-secondary-content">
                      <span class="label background-color--primary">3 new</span>
                    </span>
            </li>
            <li class="mdl-menu__item mdl-list__item">
                    <span class="mdl-list__item-primary-content">
                        <i class="material-icons mdl-list__item-icon">perm_contact_calendar</i>
                        My events
                    </span>
            </li>
            <li class="list__item--border-top"></li>
            <li class="mdl-menu__item mdl-list__item">
                    <span class="mdl-list__item-primary-content">
                        <i class="material-icons mdl-list__item-icon">settings</i>
                        Settings
                    </span>
            </li>
            <li class="mdl-menu__item mdl-list__item">
                    <span class="mdl-list__item-primary-content">
                        <i class="material-icons mdl-list__item-icon text-color--secondary">exit_to_app</i>
                        Log out
                    </span>
            </li>
        </ul>

        <button id="more"
                class="mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">more_vert</i>
        </button>

        <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect mdl-shadow--2dp settings-dropdown"
            for="more">
            <li class="mdl-menu__item">
                Settings
            </li>
            <a class="mdl-menu__item" href="https://github.com/CreativeIT/getmdl-dashboard/issues">
                Support
            </a>
            <li class="mdl-menu__item">
                F.A.Q.
            </li>
        </ul>
    </div>
</header>

templates/assets/menu.html
<div class="mdl-layout__drawer">
    <header>darkboard</header>
    <nav class="mdl-navigation">
        <a class="mdl-navigation__link mdl-navigation__link--current" href="{% url 'index' %}">
            <i class="material-icons" role="presentation">dashboard</i>
            Dashboard
        </a>

        <a class="mdl-navigation__link" href="{% url 'inscripcion:eventos' %}">
            <i class="material-icons" role="presentation">map</i>
            Evento
        </a>

        <a class="mdl-navigation__link" href="{% url 'configuracion:acceso_listar' %}">
            <i class="material-icons" role="presentation">map</i>
            Conección Api
        </a>

        <div class="mdl-layout-spacer"></div>
        <a class="mdl-navigation__link" href="https://github.com/CreativeIT/getmdl-dashboard">
            <i class="material-icons" role="presentation">link</i>
            GitHub
        </a>
    </nav>
</div>

templates/base.html
{% load static %}
<!doctype html>
<!--
  Material Design Lite
  Copyright 2015 Google Inc. All rights reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License
-->
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <link rel="icon" type="image/png" href="images/DB_16х16.png">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Material Dashboard Lite</title>

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">


    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Material Design Lite">


    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
    <meta name="msapplication-TileColor" content="#3372DF">

    <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
    <!--
    <link rel="canonical" href="http://www.example.com/">
    -->

    <link href='https://fonts.googleapis.com/css?family=Roboto:400,500,300,100,700,900' rel='stylesheet'
          type='text/css'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'custom/css/lib/getmdl-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'custom/css/lib/nv.d3.css' %}">
    <link rel="stylesheet" href="{% static 'custom/css/application.css' %}">
    <!-- endinject -->

</head>
<body>
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
    {% include "assets/header.html" %}
    {% include "assets/menu.html" %}

    <main class="mdl-layout__content mdl-color--grey-100">

        {% block content %}

        {% endblock content %}

    </main>
</div>

<!-- inject:js -->
<script src="{% static 'custom/js/d3.js' %}"></script>
<script src="{% static 'custom/js/getmdl-select.min.js' %}"></script>
<script src="{% static 'custom/js/material.js' %}"></script>
<script src="{% static 'custom/js/nv.d3.js' %}"></script>
<script src="{% static 'custom/js/layout/layout.js' %}"></script>
<script src="{% static 'custom/js/widgets/charts/chart1.js' %}"></script>
<script src="{% static 'custom/js/widgets/charts/chart2.js' %}"></script>
<script src="{% static 'custom/js/widgets/charts/discreteBarChart.js' %}"></script>
<script src="{% static 'custom/js/widgets/employer-form/employer-form.js' %}"></script>
<script src="{% static 'custom/js/widgets/line-chart/line-chart-nvd3.js' %}"></script>
<script src="{% static 'custom/js/widgets/map/maps.js' %}"></script>
<script src="{% static 'custom/js/widgets/pie-chart/pie-chart-nvd3.js' %}"></script>
<script src="{% static 'custom/js/widgets/table/table.js' %}"></script>
<script src="{% static 'custom/js/widgets/todo/todo.js' %}"></script>
<!-- endinject -->

</body>
</html>